CREATE TYPE public.role_category AS ENUM ('editor', 'admin');
CREATE TYPE public.status AS ENUM ('active', 'inactive');

create table public.books (
  id bigint generated by default as identity not null,
  title text not null default ''::text,
  description text null default ''::text,
  price real null default 1,
  author text null default ''::text,
  image text not null default ''::text,
  format text null,
  pages integer null,
  "bookBinding" text null,
  isbn text not null default ''::text,
  resume text null,
  especiality jsonb null,
  state public.status null default 'inactive'::status,
  "dateUpload" timestamp with time zone null,
  constraint books_pkey primary key (id),
  constraint books_isbn_key unique (isbn)
) TABLESPACE pg_default;

create table public.users (
  id bigint generated by default as identity not null,
  name text null default ''::text,
  email text null default ''::text,
  password text null,
  role public.role_category not null default 'editor'::role_category,
  constraint users_pkey primary key (id)
) TABLESPACE pg_default;